server:
  port: 80

#Turn this on to enable HTTPS
#server:
#  port: 8443
#  ssl:
#    key-store: target/classes/keystore.jks
#    key-store-password: password
#    keyStoreType: PKCS12
#    keyAlias: selfsigned

logging:
  level.: INFO
